module RuboCop
  module Cop
    module Codemod
      # KeepUnique
      class KeepUnique < Base
        extend AutoCorrector
        include IgnoredNode

        @commands: Hash[Integer, String]

        MSG: String

        COMMAND: String

        def initialize: (*untyped args) -> void

        def on_new_investigation: () -> void

        def command_exists?: (RuboCop::AST::Node node) -> bool

        def on_array: (RuboCop::AST::ArrayNode node) -> void
      end
    end
  end
end
