module RuboCop
  module Cop
    module Codemod
      # KeepUnique
      class KeepUnique < Base
        extend AutoCorrector
        include IgnoredNode

        @commands: Hash[Integer, String]

        MSG: "Keep array items unique, removing duplicates."

        COMMAND: "keep-unique"

        def initialize: (*untyped args) -> void

        def on_new_investigation: () -> untyped

        def command_exists?: (untyped node) -> untyped

        def on_array: (untyped node) -> (nil | untyped)
      end
    end
  end
end
