module RuboCop
  module Cop
    module Codemod
      # KeepUnique
      class RbsPrototype < Base
        @commands: untyped

        extend AutoCorrector

        MSG: String

        COMMAND: String

        def initialize: (*untyped args) -> void

        def find_node_on_line: (RuboCop::AST::Node? node, Integer target_line) -> (RuboCop::AST::Node | nil)

        def on_new_investigation: () -> void
      end
    end
  end
end
